merge (#14)
* video_core: Remove redundant pixel format type

We already get the format type before converting shadow formats and during shadow formats.

* am: Unstub SetScreenShotPermission

* ci: Make use of clang-format 10.0

10.0 seems to play nicer with C++ attributes compared to clang-format
6.0.

* game_list_worker: Do not clear entries when > 1 gamedir is present

Previously the map of entries was being cleared while looping through each game directory, this resulted into all game directories except the last game dir to lose content metadata information. Fix this by clearing the entries only once.

* vfs_vector: Make creation of array vfs files less verbose

We can add a helper function to make creation of these files nicer.
While we're at it, we can eliminate an unnecessary std::array copy in
the constructor. This makes the overhead on some of these functions way
less intensive, given some arrays were quite large.

e.g. The timezone location names are 9633 bytes in size.

* address_arbiter: Resolve sign conversion warning

Makes our type conversion explicit.

* scheduler: Resolve sign conversion warning

* kernel: Remove unused variables

Resolves a few compiler warnings.

* common/virtual_buffer: drop unused includes

On DragonFly and NetBSD build fails with

src/common/virtual_buffer.cpp
src/common/virtual_buffer.cpp:16:10: fatal error: sys/sysinfo.h: No such file or directory
 #include <sys/sysinfo.h>
          ^~~~~~~~~~~~~~~

* partition_data_manager: Make data arrays constexpr

Previously the constructor for all of these would run at program
startup, consuming time before the application can enter main().

This is also particularly dangerous, given the logging system wouldn't
have been initialized properly yet, yet the program would use the logs
to signify an error.

To rectify this, we can replace the literals with constexpr functions
that perform the conversion at compile-time, completely eliminating the
runtime cost of initializing these arrays.

* partition_data_manager: Update master key hashes

Fills in some hashes that were previously unhandled.

* cheat_engine: Make use of designated initializers

Same behavior, but makes the member being assigned obvious.

* freezer: Make use of std::erase_if

With C++20 we can simplify the erasing idiom.

* freezer: Take address values by value

VAddr will always be 64-bit, so there's no need to take a trivial
primitive alias by reference.

* freezer: Move entry finding to its own function

Cleans up the callsites in other functions.

* common/concepts: Rename IsBaseOf to DerivedFrom

This makes it more inline with its currently unavailable standardized
analogue std::derived_from.

While we're at it, we can also make the template match the requirements
of the standardized variant as well.

* General: Tidy up clang-format warnings

* Add range slider for analog sticks

* Address c++20 warning, fix inaccurate range text display when slide == 0

* undo unnecessary newlines, slider range 50-150

* Add range slider functionality for gc adapter

* Remove UI changes

This PR is now only the Analog devices handling the range value defaulting at 100%

Co-authored-by: David Marcec <dmarcecguzman@gmail.com>
Co-authored-by: Lioncash <mathew1800@gmail.com>
Co-authored-by: Morph <39850852+Morph1984@users.noreply.github.com>
Co-authored-by: Jan Beich <jbeich@FreeBSD.org>
Co-authored-by: bunnei <bunneidev@gmail.com>
Co-authored-by: David <25727384+ogniK5377@users.noreply.github.com>
Co-authored-by: Ameer <aj662@drexel.edu>